"""Add video_title field to Task model

Revision ID: 6422d4b98917
Revises: b8b08a6a7fec
Create Date: 2026-01-20 20:42:25.300083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6422d4b98917'
down_revision: Union[str, Sequence[str], None] = 'b8b08a6a7fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_title', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('video_title')

    # ### end Alembic commands ###
